name: Deploy Speakify API with ngrok

on:
  push:
    branches:
      - main  # Run workflow on push to main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyngrok  # Install ngrok

    - name: Configure ngrok Auth Token
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Run Speakify API with ngrok
      run: |
        python main.py   # Run API in background
        sleep 10  # Wait for ngrok to start
        curl http://127.0.0.1:8000  # Check if API is running
